# ECG Heartbeat Classification

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [3]:
normal = pd.read_csv("../ECG Dataset/ptbdb_normal.csv", header = None)
abnormal = pd.read_csv("../ECG Dataset/ptbdb_abnormal.csv", header = None)

In [4]:
dataset = pd.concat([normal, abnormal], ignore_index=True)
dataset

,0,1,2,3,4,5,6,7,8,9,...,178,179,180,181,182,183,184,185,186,187
0,1.000000,0.900324,0.358590,0.051459,0.046596,0.126823,0.133306,0.119125,0.110616,0.113047,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.000000,0.794681,0.375387,0.116883,0.000000,0.171923,0.283859,0.293754,0.325912,0.345083,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.909029,0.791482,0.423169,0.186712,0.000000,0.007836,0.063032,0.077002,0.074957,0.077342,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.000000,0.478893,0.056760,0.064176,0.081289,0.072732,0.055619,0.048774,0.054478,0.041643,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.000000,0.867238,0.201360,0.099349,0.141336,0.120934,0.108516,0.096393,0.093436,0.100828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14547,0.981409,1.000000,0.559171,0.287093,0.196639,0.204862,0.215946,0.243833,0.242760,0.250268,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14548,0.906250,0.922379,0.878024,0.810484,0.712702,0.667339,0.608871,0.527218,0.480847,0.442540,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14549,1.000000,0.867971,0.674122,0.470332,0.296987,0.169307,0.077664,0.081392,0.074868,0.089779,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14550,1.000000,0.984672,0.658888,0.556394,0.446809,0.395790,0.315260,0.276367,0.261039,0.258522,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0


## Check if any value is Null

In [5]:
print(dataset.isnull().values.any())
print(dataset.isna().values.any())

False
False


In [6]:
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

In [7]:
print(y.value_counts())

187
1.0    10506
0.0     4046
Name: count, dtype: int64


## Train-Test Split

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1) # seeding the dataset with '1'
X_train, X_test, y_train, y_test

(            0         1         2         3         4         5         6    \
 2313   0.920422  1.000000  0.479288  0.228561  0.031613  0.065044  0.129724   
 10009  0.897787  0.652266  0.074816  0.037935  0.030558  0.134879  0.295047   
 4960   1.000000  0.968713  0.634748  0.539227  0.429960  0.374259  0.280161   
 11757  0.902920  0.991318  0.894238  0.826361  0.743489  0.676401  0.631413   
 6112   1.000000  0.669126  0.339891  0.181148  0.152186  0.137978  0.103005   
 ...         ...       ...       ...       ...       ...       ...       ...   
 905    1.000000  0.919740  0.630803  0.315401  0.116269  0.007809  0.077223   
 5192   1.000000  0.595851  0.351912  0.158210  0.134466  0.107473  0.076731   
 12172  0.930952  0.764881  0.376190  0.250595  0.263095  0.197024  0.144048   
 235    1.000000  0.929658  0.372243  0.071483  0.077947  0.146008  0.148289   
 13349  1.000000  0.502685  0.042965  0.192266  0.245972  0.255639  0.191192   
 
             7         8         9    

In [9]:
print(y_train.value_counts())
print(y_test.value_counts())

187
1.0    8408
0.0    3233
Name: count, dtype: int64
187
1.0    2098
0.0     813
Name: count, dtype: int64


## Feature Scaling

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)   # Learn min/max from training data
X_test = scaler.transform(X_test)         # Use the same min/max for test data

In [11]:
X_train, X_test

(array([[0.78822705, 1.        , 0.4792878 , ..., 0.        , 0.        ,
         0.        ],
        [0.72799277, 0.65226555, 0.07481559, ..., 0.        , 0.        ,
         0.        ],
        [1.        , 0.96871299, 0.63474756, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.81625153, 0.76488096, 0.37619048, ..., 0.        , 0.        ,
         0.        ],
        [1.        , 0.92965782, 0.37224334, ..., 0.        , 0.        ,
         0.        ],
        [1.        , 0.50268531, 0.04296456, ..., 0.        , 0.        ,
         0.        ]], shape=(11641, 187)),
 array([[1.        , 0.91621327, 0.8726877 , ..., 0.        , 0.        ,
         0.        ],
        [0.85200551, 0.80816329, 0.39693877, ..., 0.        , 0.        ,
         0.        ],
        [0.96299959, 0.10160428, 0.12513369, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.83885171, 0.57190919, 0.08284272, ..., 0.        , 0.        ,
         0.   

## Know the `class_weight`

In [12]:
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(y_train)

weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y_train
)

class_weights = dict(zip(classes, weights))

print(class_weights)

{np.float64(0.0): np.float64(1.8003402412619858), np.float64(1.0): np.float64(0.6922573739295909)}


## Reshape the data for LSTM

In [13]:
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

In [14]:
print(X_train.shape)
print(X_test.shape)

(11641, 187, 1)
(2911, 187, 1)


## Build LSTM

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

I0000 00:00:1784034559.668144   18583 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    LSTM,
    Dense,
    Dropout,
    BatchNormalization
)
from tensorflow.keras.optimizers import Adam

model = Sequential()

# First LSTM Layer
model.add(LSTM(128, return_sequences=True, input_shape=(187, 1)))
model.add(BatchNormalization())
model.add(Dropout(0.3))

# Second LSTM Layer
model.add(LSTM(64, return_sequences=True))
model.add(BatchNormalization())
model.add(Dropout(0.3))

# Third LSTM Layer
model.add(LSTM(32))
model.add(BatchNormalization())
model.add(Dropout(0.3))

# Dense Layers
model.add(Dense(64, activation="relu"))
model.add(Dropout(0.2))

model.add(Dense(32, activation="relu"))
model.add(Dropout(0.2))

# Output Layer
model.add(Dense(1, activation="sigmoid"))

# Compile
optimizer = Adam(learning_rate=0.0005)

model.compile(
    optimizer=optimizer,
    loss="binary_crossentropy",
    metrics=[
        "accuracy"
    ]
)

model.summary()

/home/programmer/PyTorch Project/myenv/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_3 (LSTM)                   │ (None, 187, 128)       │        66,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 187, 128)       │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 187, 128)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (None, 187, 64)        │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 187, 64)        │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 187, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 32)             │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 133,505 (521.50 KB)

 Trainable params: 133,057 (519.75 KB)

 Non-trainable params: 448 (1.75 KB)

In [31]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_3 (LSTM)                   │ (None, 187, 128)       │        66,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 187, 128)       │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 187, 128)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (None, 187, 64)        │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 187, 64)        │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 187, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 32)             │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 133,505 (521.50 KB)

 Trainable params: 133,057 (519.75 KB)

 Non-trainable params: 448 (1.75 KB)

## Train the model

In [32]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=50,
    callbacks=[early_stop]
)

Epoch 1/50
364/364 ━━━━━━━━━━━━━━━━━━━━ 67s 173ms/step - accuracy: 0.6845 - loss: 0.6256 - val_accuracy: 0.7235 - val_loss: 0.5701
Epoch 2/50
364/364 ━━━━━━━━━━━━━━━━━━━━ 65s 178ms/step - accuracy: 0.7212 - loss: 0.5616 - val_accuracy: 0.6956 - val_loss: 0.5871
Epoch 3/50
364/364 ━━━━━━━━━━━━━━━━━━━━ 65s 178ms/step - accuracy: 0.7239 - loss: 0.5273 - val_accuracy: 0.7331 - val_loss: 0.5012
Epoch 4/50
364/364 ━━━━━━━━━━━━━━━━━━━━ 66s 181ms/step - accuracy: 0.7320 - loss: 0.5056 - val_accuracy: 0.7351 - val_loss: 0.5451
Epoch 5/50
364/364 ━━━━━━━━━━━━━━━━━━━━ 65s 178ms/step - accuracy: 0.7600 - loss: 0.4806 - val_accuracy: 0.7290 - val_loss: 0.5171
Epoch 6/50
364/364 ━━━━━━━━━━━━━━━━━━━━ 65s 178ms/step - accuracy: 0.7678 - loss: 0.4631 - val_accuracy: 0.7059 - val_loss: 0.5679
Epoch 7/50
364/364 ━━━━━━━━━━━━━━━━━━━━ 66s 180ms/step - accuracy: 0.7869 - loss: 0.4515 - val_accuracy: 0.8066 - val_loss: 0.4234
Epoch 8/50
364/364 ━━━━━━━━━━━━━━━━━━━━ 65s 179ms/step - accuracy: 0.8104 - loss: 0

## Classification Report

In [33]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5).astype(int)
y_pred = y_pred.ravel()

print(classification_report(y_test, y_pred))

91/91 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step
              precision    recall  f1-score   support

         0.0       0.95      0.90      0.93       813
         1.0       0.96      0.98      0.97      2098

    accuracy                           0.96      2911
   macro avg       0.96      0.94      0.95      2911
weighted avg       0.96      0.96      0.96      2911



In [34]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[ 733   80]
 [  35 2063]]


In [ ]:
# model.save_weights("lstm_weights.weights.h5")